In [29]:
from bs4 import BeautifulSoup
import requests
import pandas as pd

In [30]:
headers={'User-Agent':'Mozilla/5.0 (Windows NT 6.3; Win 64 ; x64) Apple WeKit /537.36(KHTML , like Gecko) Chrome/80.0.3987.162 Safari/537.36'}
webpage = requests.get("https://www.ambitionbox.com/list-of-companies?page=1", headers=headers).text

In [31]:
soup = BeautifulSoup(webpage, 'lxml')

In [32]:
company = soup.find_all('div', class_="companyCardWrapper")

In [33]:
len(company)

20

In [35]:
name = []
rating = []
reviews = []
cinfo = []
for i in company:
    
    name.append(i.find('h2').text.strip())
    rating.append(i.find('div', class_= "companyCardWrapper__companyRatingWrapper").text.strip())
    reviews.append(i.find('span', class_="companyCardWrapper__ActionCount").text.strip())
    cinfo.append(i.find('span', class_="companyCardWrapper__interLinking").text.strip())
    

d = {'name':name,
     'rating':rating,
     'reviews':reviews,
     'cinfo':cinfo}
    
df = pd.DataFrame(d)
df

,name,rating,reviews,cinfo
0,TCS,3.8,66.9k,IT Services & Consulting | 1 Lakh+ Employees |...
1,Accenture,4.1,42.7k,IT Services & Consulting | 1 Lakh+ Employees |...
2,Cognizant,3.9,38.5k,IT Services & Consulting | 1 Lakh+ Employees |...
3,Wipro,3.8,35.5k,IT Services & Consulting | 1 Lakh+ Employees |...
4,ICICI Bank,4.0,31k,Banking | 1 Lakh+ Employees | Public | 29 year...
5,HDFC Bank,3.9,30.7k,Banking | 1 Lakh+ Employees | Public | 29 year...
6,Infosys,3.9,29.2k,IT Services & Consulting | 1 Lakh+ Employees |...
7,Capgemini,3.8,27.1k,IT Services & Consulting | 1 Lakh+ Employees |...
8,Tech Mahindra,3.7,25.4k,IT Services & Consulting | 1 Lakh+ Employees |...
9,HCLTech,3.7,24.9k,IT Services & Consulting | 1 Lakh+ Employees |...
10,Genpact,3.9,24.3k,IT Services & Consulting | 1 Lakh+ Employees |...
11,Axis Bank,3.8,20.4k,Banking | 50k-1 Lakh Employees | Public | 30 y...
12,Concentrix Corporation,3.9,20.1k,BPO | 50k-1 Lakh Employees | Public | 40 years...
13,Amazon,4.1,19.3k,Internet | 1 Lakh+ Employees | Public | 29 yea...
14,Reliance Jio,3.9,18.6k,Telecom | 50k-1 Lakh Employees | Public | 16 y...
15,IBM,4.1,18.6k,Software Product | 50k-1 Lakh Employees | Publ...
16,Larsen & Toubro Limited,4.0,17.4k,Engineering & Construction | 10k-50k Employees...
17,Reliance Retail,3.9,16.8k,Retail | 1 Lakh+ Employees | 17 years old | Na...
18,HDB Financial Services,4.0,16.4k,NBFC | 1 Lakh+ Employees | 16 years old | Ahme...
19,Teleperformance,3.6,15.9k,BPO | 50k-1 Lakh Employees | Forbes Global 200...

In [15]:
salaries

['66.8k Reviews',
 '42.6k Reviews',
 '38.5k Reviews',
 '35.5k Reviews',
 '31k Reviews',
 '30.7k Reviews',
 '29.2k Reviews',
 '27.1k Reviews',
 '25.4k Reviews',
 '24.9k Reviews',
 '24.3k Reviews',
 '20.4k Reviews',
 '20.1k Reviews',
 '19.3k Reviews',
 '18.6k Reviews',
 '18.6k Reviews',
 '17.4k Reviews',
 '16.8k Reviews',
 '16.4k Reviews',
 '15.8k Reviews']

In [40]:
final=pd.DataFrame()

for j in range(1,500):
    
    
    url="https://www.ambitionbox.com/list-of-companies?page={}".format(j)
    
    headers={'User-Agent':'Mozilla/5.0 (Windows NT 6.3; Win 64 ; x64) Apple WeKit /537.36(KHTML , like Gecko) Chrome/80.0.3987.162 Safari/537.36'}
    webpage = requests.get(url, headers=headers).text
    
    
    soup = BeautifulSoup(webpage, 'lxml')
    
    company = soup.find_all('div', class_="companyCardWrapper")
    
    name = []
    rating = []
    reviews = []
    cinfo = []
    
    for i in company:
        name.append(i.find('h2').text.strip())
        rating.append(i.find('div', class_= "companyCardWrapper__companyRatingWrapper").text.strip())
        reviews.append(i.find('span', class_="companyCardWrapper__ActionCount").text.strip())
        cinfo.append(i.find('span', class_="companyCardWrapper__interLinking").text.strip())
    

    d = {'name':name, 'rating':rating, 'reviews':reviews, 'cinfo':cinfo}
    df = pd.DataFrame(d)
    
    
    final = final.append(df,ignore_index=True)

AttributeError: 'DataFrame' object has no attribute 'append'